# Generated by Django 5.0.6 on 2024-07-08 14:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('question_type', models.CharField(choices=[('MOOD', 'Mood'), ('PERSONALITY', 'Personality'), ('CONTEXTUAL', 'Contextual')], max_length=15)),
                ('mood', models.CharField(blank=True, max_length=100, null=True)),
                ('submood', models.CharField(blank=True, max_length=100, null=True)),
                ('trait', models.CharField(blank=True, max_length=100, null=True)),
                ('facet', models.CharField(blank=True, max_length=100, null=True)),
                ('choices', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user_name', models.CharField(max_length=100)),
                ('user_mood', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('user_submood', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('user_personality', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('user_personality_degree', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('user_subpersonality', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('user_activity', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('user_location', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('user_timeofday', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('user_social_context', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answer_text', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inferenceengine.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inferenceengine.user')),
            ],
        ),
    ]
